stages:
  - build
  - deploy

frontend:
  image: node:12.18-alpine3.12
  stage: build
  script:
    # git is required for yarn to be able to checkout the shared components
    - apk add --no-cache git
    - sh ./build/setup_headers.sh
    - yarn install
    - yarn lint
    - yarn test
    - yarn build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-node
    paths:
      - frontend/node_modules/
  artifacts:
    paths:
      - build/bundle.js
    reports:
      junit: junit.xml
  tags:
    - gnm
    - docker
  only:
    - master
    - merge_requests

validationtool:
  image: golang:1.15-alpine
  stage: build
  script:
    - cd menuvalidator
    - go build
  artifacts:
    paths:
      - menuvalidator/menu-validator
  tags:
    - gnm
    - docker
  only:
    - master
    - merge_requests

deploy:
  image: docker:19.03.11
  stage: deploy
  services:
    - docker:19.03.11-dind
  before_script:
    - docker login -u ${DOCKER_USER} -p "${DOCKER_PAT}"

  script:
    - cd build
    - cp ../menuvalidator/menu-validator .
    - docker build . -t "guardianmultimedia/pluto-start:$CI_PIPELINE_IID"
    - docker push "guardianmultimedia/pluto-start:$CI_PIPELINE_IID"
    - "echo ci_commit_branch: \\\"${CI_COMMIT_BRANCH}\\\" >> build-info.yaml"
    - "echo ci_commit_ref_name: ${CI_COMMIT_REF_NAME} >> build-info.yaml"
    - "echo ci_commit_sha: ${CI_COMMIT_SHA} >> build-info.yaml"
    - "echo ci_commit_timestamp: ${CI_COMMIT_TIMESTAMP} >> build-info.yaml"
    - "echo ci_commit_title: \\\"${CI_COMMIT_TITLE}\\\" >> build-info.yaml"
    - "echo ci_job_url: ${CI_JOB_URL} >> build-info.yaml"
    - "echo ci_project_name: ${CI_PROJECT_NAME} >> build-info.yaml"
    - "echo ci_merge_request_project_url: \\\"${CI_MERGE_REQUEST_PROJECT_URL}\\\" >> build-info.yaml"
    - "echo ci_merge_request_title: \\\"${CI_MERGE_REQUEST_TITLE}\\\" >> build-info.yaml"
    - "echo ci_pipeline_iid: ${CI_PIPELINE_IID} >> build-info.yaml"
    - "echo built_image: guardianmultimedia/pluto-start:$CI_PIPELINE_IID >> build-info.yaml"
  artifacts:
    paths:
      - build/build-info.yaml
  tags:
    - gnm
    - docker
  only:
    - master
    - merge_requests
